### ISSUE TITLE
Can't find the last locus in sheme

### ISSUE THREAD

**Issue by Dong-Ning** [bvalot/pyMLST#1]
Hi

I ran the command for A. baumanii MLST:
claMLST_create_database.py Ab_oxford_MLST_database AB_MLST_scheme.txt cpn60.fas gdhB.fas gltA.fas gpi.fas gyrB.fas recA.fas rpoD.fas 

But keep getting the same error:
Traceback (most recent call last):
  File "./claMLST_create_database.py", line 48, in <module>
    raise Exception("Gene " + name + " not found in sheme\n"+ " ".join(header))
Exception: Gene rpoD not found in sheme
ST gltA gyrB gdhB recA cpn60 gpi     rpoD

I checked my scheme file and could not find the mistakes. Can you help me? Thanks. Here is the first a few lines of the scheme file:

ST      gltA    gyrB    gdhB    recA    cpn60   gpi         rpoD
1       1       1       1       1       1       1       6
2       2       2       2       1       1       2       7
3       1       1       1       1       2       1       4
4       1       12      3       2       2       7       3
5       1       3       3       2       2       3       1
6       1       4       3       2       2       3       3
7       3       3       3       2       3       3       8
8       4       4       4       4       4       5       9
9       1       3       3       2       2       6       8
10      1       4       3       2       2       7       3
11      4       11      6       1       7       8       6
12      8       4       4       4       4       5       5
13      1       7       8       9       1       4       14
14      1       10      8       6       1       4       14
15      1       12      11      10      1       9       4
16      10      12      4       11      11      9       5
17      1       12      12      11      4       10      3
18      10      13      4       11      12      11      5
19      1       14      3       2       2       9       3
20      1       15      13      12      4       12      2
21      1       12      3       2       2       9       3
22      1       15      13      12      4       12      37
23      1       1       1       1       1       28      10
24      1       1       22      1       4       20      16
25      1       1       41      6       23      31      26
26      1       10      36      22      20      4       24
27      1       51      1       36      1       98      6
28      1       12      3       2       2       35      4
29      1       12      3       28      2       29      4
30      1       12      3       29      2       34      4

**Comment by bvalot** [comment]
Hi, 

Can you send me the schema you use or you download it from pubMLST?

Benoit

**Comment by Dong-Ning** [comment]
I uploaded the schema file here：

https://figshare.com/s/ebd2e118d0ae3a77e95d

I also tried other MLST schema including Klebsiella, Aeromonas... The same errors occurred. Thank you for your help.

**Comment by Dong-Ning** [comment]
Dear Benoit,

I send you the link on github but found it inaccessible. Please find the attached schema file. Thank you for your help.


Best regards,

DONG Ning

Y1123, Block Y
Department of Applied Biology and Chemical Technology
The Hong Kong Polytechnic University
Hung Hom, Kowloon, Hong Kong

________________________________

**Comment by bvalot** [comment]
I'm sorry, but I can not access to you file.  

You must be careful with pubmlst schema that contained some time extra columns.

**Comment by bvalot** [comment]
You can no simply import MLST scheme with the new version of pyMLST
