### ISSUE TITLE
Error: BLAT binary was not found/KMA binary was not found

### ISSUE THREAD

**Issue by sunx0766** [bvalot/pyMLST#10]
Hi Benoit,

Thanks for your quick response regarding issue #9, however, another problem has arose when I tried to add my strains to the database. My input was:
`wgMLST add strep.db seq_of_interest.fna
`
where strep.db was creating following your instruction on issue #9, and seq_of_interest.fna is my genome fasta file. The error message I got was:
`Error: BLAT binary was not found`. 

I also tried using raw reads files with the wgMLST add2 option. My input was:
`wgMLST add2 strep.db raw_R1_fastq.gz raw_R2_fastq.gz
`where the fastq files are raw illumina reads. I then got this error:
`Error: KMA binary was not found
`
Could you kindly point me to where could have gone wrong?

Thanks,
Erica

**Comment by bvalot** [comment]
Hello Erika,

You need to install other tools that depends pyMLST.
[https://github.com/bvalot/pyMLST#dependancy](https://github.com/bvalot/pyMLST#dependancy)

If you have conda, you can install pyMLST and dependancy directly:
[https://github.com/bvalot/pyMLST#automatic-installation](https://github.com/bvalot/pyMLST#automatic-installation)

**Comment by sunx0766** [comment]
Hi Benoit,

The problem is solved now, and I have successfully ran wgMLST :) Thank you again for such a great tool!

I wasn't able to do conda install and kept getting the errors like this:
```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                       
failed
UnsatisfiableError:
```
I ended up having to update my .bashrc and .condarc files. Hope this may help whoever encounter the same problem in the future!

**Comment by bvalot** [comment]
Thx for the reply.

In fact, I forgot a dependency of channel for this installation. The correct command line was:
`conda install -c bioconda -c conda-forge pymlst
`
