### ISSUE TITLE
Mycobacteria cgMLST Typing

### ISSUE THREAD

**Issue by mweberr** [bvalot/pyMLST#16]
Hi,
I am trying to reproduce the results from PubMLST Typing using cgMLST Mycobacteria sp.
The wgMLST import seems to work fine but once I use wgMLST add, no results are returned.

The original result from pubmlst.org is :
Closest profile
    cgST-12 
Mismatches
    21

How to improve the mapping ?

Best, Michael

**Comment by bvalot** [comment]
Hi,

cgMLST  analysis is dedicated to performed differential analysis between strains to determined their closeness. 
After add your strains to the database, you must use other command to obtained comparison:
wgMLST distance
wgMLST mlst

**Comment by mweberr** [comment]
Thanks for your answer. I will try
