### ISSUE TITLE
problem downloading pyMLST

### ISSUE THREAD

**Issue by aymericola** [bvalot/pyMLST#17]
Hi, 
I wanted to build a new MLST scheme and it seemed possible with pyMLST. 
Hence, I tried to download it using pip  22.0.2. (on Python 3.10) on Linux.

But I got the following error doing so. 

`ERROR: Cannot install pymlst==2.0.1, pymlst==2.1.0, pymlst==2.1.1, pymlst==2.1.2 and pymlst==2.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    pymlst 2.1.3 depends on questionary~=1.9.0
    pymlst 2.1.2 depends on questionary~=1.9.0
    pymlst 2.1.1 depends on questionary~=1.9.0
    pymlst 2.1.0 depends on questionary~=1.9.0
    pymlst 2.0.1 depends on questionary~=1.9.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

I went back to see the requirements.txt file. 
biopython>=1.78
click>=7.1
pytest>=6.2
sqlalchemy>=1.4,<2
networkx>=2.5
decorator>=4.4
requests>=2.23
pandas>=1.2
numpy>=1.20
beautifulsoup4>=4.9
questionary>=1.9
setuptools>=44.0
alembic>=1.6

It appears that questionary >=1.9 is required which I have (questionary-1.10.0). 
But there must be a conflict somewhere with other requirements, I can't seem to figure out which one.
If someone can help me on this one, that'd be great.

**Comment by bvalot** [comment]
Hi,

Yes, the problems is link to older requirement file that was not compatible with python 3.10. I make correction on the github, but I not make a new pypi package yet.

You can try to install it with conda, that must works or manually in waiting that I make this new package
