### ISSUE TITLE
Error: BLAT binary was not found

### ISSUE THREAD

**Issue by charlie-durant** [bvalot/pyMLST#18]
Hello, similarly to #11 I also have an issue with a BLAT error.

I was not able to install successfully using `conda install -c bioconda -c conda-forge pymlst`, but `pip install pymlst` seemed to work fine. 

I have also made sure the packages listed in `requirements.txt` are installed. Updating .bashrc did not solve the issue as in #10 .

**claMLST**
I seem to create the database from import fine with no errors:

`claMLST import test.db`

After selecting an option (staphylococcus aureus) from the presented list:

`? (136) Results found staphylococcus aureus
[INFO: 2023-11-08 11:09:05,973] One element found : mlst
[INFO: 2023-11-08 11:09:05,974] Downloading mlst...
[INFO: 2023-11-08 11:09:11,085] Database initialized`

When trying to perform a search:
`claMLST search test.db Staphylococcus_aureus_test.fa`

I encounter an error `BLAT binary was not found`:

`[INFO: 2023-11-08 11:13:29,404] Search ST from files: Staphylococcus_aureus_test.fa
[INFO: 2023-11-08 11:13:29,404] Search coregene with BLAT for Staphylococcus_aureus_test
Error: BLAT binary was not found`

**wgMLST**
Similarly with wgMLST, I import the database without issues:

`wgMLST import test.db`

After selecting an option (Staphylococcus aureus) from the presented list:

`[INFO: 2023-11-08 11:16:13,023] 30 elements found, please choose one:
? (30) Results found Staphylococcus aureus
[INFO: 2023-11-08 11:16:18,038] Downloading the core genome...
[INFO: 2023-11-08 11:16:36,188] Reverse-complemented genes: 961
[INFO: 2023-11-08 11:16:36,191] Database initialized`

But when trying to add strains to the database:
`wgMLST add test.db Staphylococcus_aureus_test.fa
[INFO: 2023-11-08 11:18:24,130] Search coregene with BLAT
Error: BLAT binary was not found`

**Comment by bvalot** [comment]
Hi,

Very strange your are not able to install by conda. Can you give me more informations?

Nevertherless, you can specify the PATH for the other binary software using the command:
`pyMLST configure -h`

For BLAT, you can specify PATH like this:
`pyMLST configure -b /path/to/blat`

**Comment by charlie-durant** [comment]
Thank you! All working once `mafft` and `blat` were installed and configured correctly. As for the `conda` installation problem, here is what happens when trying to install into a new conda environment:

```
conda install -c bioconda -c conda-forge pymlst
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.31=0
  - pymlst -> click[version='>=7.1'] -> __unix
  - pymlst -> click[version='>=7.1'] -> __win
  - pymlst -> mafft[version='>=7.3'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

Note that strict channel priority may have removed packages required for satisfiability.```
