### ISSUE TITLE
Spelling mistake in recombination sub-command

### ISSUE THREAD

**Issue by charlie-durant** [bvalot/pyMLST#19]
Followed documentation [here](https://pymlst.readthedocs.io/en/latest/documentation/cgmlst/other_analysis.html#recombination) to perform recombination analysis.

`wgMLST recombination -h`

This command results in:
`Error: Unknown sub-command 'recombination'`

command that works is `wgMLST recombinaison -h`

```
Usage: wgMLST recombinaison [OPTIONS] GENES ALIGNMENT

  Search potential gene re-combinations from wgMLST database export.

Options:
  -o, --output FILENAME  Output number of variations by genes
                         (default:stdout).
  -h, --help             Show this message and exit.
```

**Comment by bvalot** [comment]
Hi Charlie,

I'm currently working on 2.1.5 release that corresponds to the publication of pyMLST in Microbials Genomics.
For this purpose, I make some spellchecking correction on the program and so in the docs.

Actually, you must use the 2.1.4 version were the command is 'recombinaison' (french word for recombination)

You can check all the command using:
`wgMLST --help`

Sorry for this, I hope upload new version soon.

**Comment by bvalot** [comment]
I push the 2.1.5 version on pypi. Update your package and normally the command name would be as the documentation

**Comment by charlie-durant** [comment]
No worries, makes sense! Thanks
