### ISSUE TITLE
multi-fasta file for scheme creation

### ISSUE THREAD

**Issue by ClaraVIS** [bvalot/pyMLST#3]
Hi,

Instead of downloading the scheme from  https://www.cgmlst.org/ I want to create one with a downloaded external file from a Core genome analysis in publication with the `wgMLST create` option.
 
I wonder how the multi-fasta file containing sequences of genes format, specifically the alleles id, should be. It seems that a multiFasta with all the allellic variants of each loci of a specific Species do not work.

Thanks

**Comment by bvalot** [comment]
Hi ClaraVIS,

You need a fasta file with the genes to create a custom schema for whole genome analysis.
`>geneA
ATGGATGCTAGT...`
`>geneB
ATGCGTCATGCTA...`

But pyMLST don't use allelic variant for each genes, so the files must contains only one allele for each genes.

**Comment by ClaraVIS** [comment]
Hello bvalot,

Thank you very much. It worked with one allele per gene.


:)

**Comment by bvalot** [comment]
OK good.
