### ISSUE TITLE
Create a database input example

### ISSUE THREAD

**Issue by sunx0766** [bvalot/pyMLST#9]
Hi there!

Thank you so much for developing this tool for MLST. I'm excited in using this tool for wgMLST however running into some problems while creating my own database for _Streptococcus agalactiae_. I was able to obtain the different allels from pubMLST in a multi-fasta format for each gene, and there are around ~1400 genes I'm interested in using for typing. How can I have the ~1400 multi-fasta files as my input? Would you be willing to provide an example of what the create database command look like? Thank you!

**Comment by bvalot** [comment]
Hello,

The most easy way to create a cg/wgMLST database for a new species is to use a annotated genome.
For you species, you can use [this genome](https://www.ncbi.nlm.nih.gov/nuccore/CP012480.1)

You need to download **genes** of this genome for input of wgMLST:
Clic on Send to -> coding sequence -> FASTA nucleotide

You use this multi-fasta as input of wgMLST create and you need to add the -r option

Hope it would be help,
Benoit

**Comment by sunx0766** [comment]
Hi Benoit,

Thank you so much, this clarified things up and worked!

Kind regards,
Erica
